pyapp/urls.py
from django.contrib import admin
from django.urls import path
from core.views import frontpage, signup
from django.contrib.auth import views
from course.views import course_detail, assign_to_course, unsign_to_course
from userprofile.views import dashboard, delete_course, add_course

urlpatterns = [
    path('', frontpage, name='frontpage'),
    path('signup/', signup, name='signup'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('login/', views.LoginView.as_view(template_name='login.html'), name='login'),
    path('admin/', admin.site.urls),
    path('courses/<int:course_id>/', course_detail, name='course_detail'),
    path('dashboard/', dashboard, name='dashboard'),
    path('dashboard/<int:course_id>/', delete_course, name='course_delete'),
    path('dashboard/add', add_course, name='add_course'),
    path('assign/<int:course_id>/', assign_to_course, name='assign'),
    path('unsign/<int:course_id>/', unsign_to_course, name="unsign")
]

core/models.py
from django.db import models

# Create your models here.

course/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Course(models.Model):
    name = models.CharField(max_length=255)
    instructor = models.ForeignKey(User, related_name='courses', on_delete=models.CASCADE)
    yt_channel = models.CharField(max_length=255)
    description = models.TextField()

    students = models.ManyToManyField(User, related_name="students", blank=True)
    # created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='userprofile', on_delete=models.CASCADE)
    is_instructor = models.BooleanField(default=False)
    # created_at = models.DateTimeField(auto_now_add=True)

User.userprofile = property(lambda  u:UserProfile.objects.get_or_create(user=u)[0])

course/forms.py
from django import forms

from .models import Course


class AddCourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'yt_channel', 'description']

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from course.models import Course
# Create your views here.
def frontpage(request):
    courses = Course.objects.all()[0:10]
    return render(request, "frontpage.html", {'courses':courses})


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            account_type = request.POST.get('account_type', 'student')
            if account_type == 'instructor':
                user.userprofile.is_instructor = True
                user.userprofile.save()
            login(request, user)
            return redirect('frontpage')
    else:
        form = UserCreationForm()
    return render(request, "signup.html", {'form': form})

course/views.py
from django.shortcuts import render, redirect
from .models import Course
# Create your views here.


def course_detail(request, course_id):
    course = Course.objects.get(pk=course_id)
    return render(request, 'course_detail.html', {'course':course})


def assign_to_course(request, course_id):
    course = Course.objects.get(pk=course_id)
    course.students.add(request.user)
    course.save()
    return redirect('frontpage')


def unsign_to_course(request, course_id):
    course = Course.objects.get(pk=course_id)
    course.students.remove(request.user)
    course.save()
    return redirect('dashboard')

userprofile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from course.models import Course
from course.forms import AddCourseForm


# Create your views here.
@login_required
def dashboard(request):
    courses = request.user.courses.all()
    assign = request.user.students.all()
    return render(request, 'dashboard.html', {'userprofile': request.user.userprofile, 'courses': courses,
                                              'assign': assign})


@login_required()
def delete_course(request, course_id):
    course = Course.objects.get(pk=course_id)
    course.delete()
    return redirect('dashboard')


@login_required()
def add_course(request):
    if request.method == 'POST':
        form = AddCourseForm(request.POST)

        if form.is_valid():
            course = form.save(commit=False)
            course.instructor = request.user
            course.save()

            return redirect('dashboard')
    else:
        form = AddCourseForm()

    return render(request, 'add_course.html', {'form': form})

core/templates/base.html
<!DOCTYPE html>

<html>
    <head>
        <!-- Meta -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Django app</title>

        <!-- Styles -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    </head>
    <body>
        <!-- Navbar -->
        <nav class="navbar is-light">
            <div class="navbar-brand">
                <a href="{% url 'frontpage' %}" class="navbar-item"><strong>Django App</strong></a>
            </div>

            <div class="navbar-brand">
                <div class="navbar-end">
                    <div class="navbar-item">
                        <div class="buttons">
                            {% if request.user.is_authenticated %}
                                <a href="{% url 'dashboard' %}" class="button is-light"><strong>Dashboard</strong></a>
                                <a href="{% url 'logout' %}" class="button is-danger">Log out</a>
                            {% else %}
                                <a href="{% url 'signup' %}" class="button is-success"><strong>Sign up</strong></a>
                                <a href="{% url 'login' %}" class="button is-light"><strong>Log in</strong></a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </nav>

        <!-- Main content -->
        <section class="section">
            {% block content %}
            {% endblock %}
        </section>

    </body>
</html>

core/templates/frontpage.html
{%  extends 'base.html' %}

{% block content %}
    <h2 class="subtitle has-text-centered">Newest courses</h2>
    <div class="columns">
        {% for course in courses %}
            <div class="column is-3">
                <div class="card">
                    <div class="card-content">
                        <div class="media">
                            <div class="media-content">
                                <p class="title is-4">{{ course.name }}</p>
                                <p class="title is-4">{{ course.instructor.email }}</p>
                            </div>
                        </div>

                        <div class="content">
                            {{ course.description }}

                            <hr>

                            <a class="button is-light" href="{% url 'course_detail' course.id %}">View</a>
                            {% if request.user.is_authenticated %}
                                <a class="button is-light" href="{% url 'assign' course.id %}">Assign</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

core/templates/login.html
{%  extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="columns">
            <h1 class="title">Log in</h1>

            <form method="post" action=".">
                {% csrf_token %}

                {{ form.as_p }}

                <div class="field">
                    <div class="control">
                        <button class="button is-success">Log in</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

core/templates/signup.html
{%  extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="columns">
            <h1 class="title">Sign up</h1>

            <form method="post" action=".">
                {% csrf_token %}

                {{ form.as_p }}

                <hr>

                <div class="field">
                    <label>Account type</label>

                    <div class="control">
                        <select name="account_type">
                            <option value="student" selected>Student</option>
                            <option value="instructor">Instructor</option>
                        </select>
                    </div>
                </div>

                <div class="field">
                    <div class="control">
                        <button class="button is-success">Sign up</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

course/templates/add_course.html
{%  extends 'base.html' %}

{% block content %}
    <h1 class="title">Add course</h1>

    <form method="post" action=".">
        {%  csrf_token %}

        {% if form.errors %}
            {% for error in form.errors %}
                <div class="notification is-danger">
                    {{ error }}
                </div>
            {% endfor %}

        {% endif %}
        <div class="field">
            <label>Name</label>
            <div class="control">
                <input class="input" type="text" name="name" id="id_name">
            </div>
        </div>

        <div class="field">
            <label>Youtube channel</label>
            <div class="control">
                <input class="input" type="text" name="yt_channel" id="id_yt_channel">
            </div>
        </div>

        <div class="field">
            <label>Description</label>
            <div class="control">
                <input class="input" type="text" name="description" id="id_description">
            </div>
        </div>

        <div class="field">
            <div class="control">
                <button class="button is-success">Submit</button>
            </div>
        </div>
    </form>
{% endblock %}

course/templates/course_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="title">{{ course.name }}</h1>
    <p class="title is-4">Instructor: {{ course.instructor.first_name }} {{ course.instructor.last_name }}</p>
    <p class="title is-4">Instructor email: {{ course.instructor.email }}</p>
    <p class="is-size-4">Instructor youtube channel: {{ course.yt_channel }}</p>
    <p class="is-size-4">{{ course.description }}</p>

{%  endblock %}

userprofile/templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="title">Dashboard</h1>

    {% if userprofile.is_instructor %}
        <hr>
        <h1 class="subtitle">My courses</h1>
        <a href="{% url 'add_course' %}" class="button is-light"><strong>Add course</strong></a>
        <div class="columns">
        {% for course in courses %}
            <div class="column is-3">
                <div class="card">
                    <div class="card-content">
                        <div class="media">
                            <div class="media-content">
                                <p class="title is-4">{{ course.name }}</p>
                                <p class="title is-4">{{ course.instructor.email }}</p>
                            </div>
                        </div>

                        <div class="content">
                            {{ course.description }}

                            <hr>

                            <a href="{% url 'course_delete' course.id%}">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% else %}
        <hr>
        <h1 class="subtitle">Assign courses</h1>
        <div class="columns">
        {% for course in assign %}
            <div class="column is-3">
                <div class="card">
                    <div class="card-content">
                        <div class="media">
                            <div class="media-content">
                                <p class="title is-4">{{ course.name }}</p>
                                <p class="title is-4">{{ course.instructor.email }}</p>
                            </div>
                        </div>

                        <div class="content">
                            {{ course.description }}

                            <hr>

                            <a href="{% url 'unsign' course.id%}">Unsign</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}